name: todo_list

services:
  angular:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: todo_list_angular
    ports:
      - "4200:4200"
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
    profiles:
      - dev

  backend:
    build:
      context: ./backend/src
      dockerfile: Dockerfile
    container_name: todo_list_backend
    ports:
      - "8090:8090"
    develop:
      watch:
        - action: sync
          path: ./backend/src
          target: /app
    profiles:
      - dev

  postgres:
    build:
      context: ./backend/src/external/db
      dockerfile: Dockerfile
    container_name: todo_list_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: todo-list-db
    ports:
      - "5432:5432"
    volumes:
      - todo_list_data_sql:/var/lib/postgresql/data
    profiles:
      - dev

  pgadmin:
    image: dpage/pgadmin4:9.9
    container_name: todo_list_pgadmin
    ports:
      - 5050:80
    volumes:
      - ./backend/src/external/db/pgpass:/config/pgpass:ro
      - ./backend/src/external/db/servers.json:/pgadmin4/servers.json:ro
    environment:
      PGADMIN_DEFAULT_EMAIL: demo@example.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    profiles:
      - dev   

volumes:
  todo_list_data_sql:
