services:
  angular-prod:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: docker-angular-sample
    ports:
      - "8080:8080"

  angular-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "4200:4200"
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app

  backend-dev:
    build:
      context: ./backend/src
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    develop:
      watch:
        - action: rebuild
          path: ./backend/src
          target: /app

