services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo_list_postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: todo-list-db
    ports:
      - "5432:5432"
    volumes:
      - data_sql:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:9.9
    container_name: todo_list_pgadmin
    ports:
      - 5050:80
    volumes:
      - ./pgpass:/config/pgpass:ro
      - ./servers.json:/pgadmin4/servers.json:ro
    environment:
      PGADMIN_DEFAULT_EMAIL: demo@example.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'   

volumes:
  data_sql:
