apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --profile prod
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: angular
  name: angular
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: angular
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --profile prod
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: angular
    spec:
      containers:
        - image: angular
          name: todo-list-angular-prod
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
