apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --profile prod
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: backend
  name: backend
spec:
  ports:
    - name: "8090"
      port: 8090
      targetPort: 8090
  selector:
    io.kompose.service: backend
